### ISSUE TITLE
Nginx config

### ISSUE THREAD

**Issue by lekkerduidelijk** [mathiasbynens/php-url-shortener#11]
Thanks for the great but simple script 😄 @mathiasbynens!
I've been using it since 2012 and have migrated it from server to server over the years.

My most recent install was on a LEMP stack and I'd like to share my current rewrite config for other users.

Use this in your `server {}` block:
```
location /shorten {
  try_files $uri $uri/ /shorten.php?$args;
}

location / {
  rewrite ^/(.*)$ /index.php?slug=$1 last;
  try_files $uri $uri/ /index.php;
}
```

Cheers!

**Comment by mathiasbynens** [comment]
Would you mind submitting a PR that adds an nginx config file alongside the existing `.htaccess`?

**Comment by mathiasbynens** [comment]
Closing in favor of #12.
